language: go
sudo: required

go:
  - 1.10.x
  - tip

service:
  - docker

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

go_import_path: github.com/src-d/regression-gitbase

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
  - sudo service mysql stop

script:
  - make dependencies
  - make test-coverage

before_deploy:
  - make packages

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - DOCKER_PUSH_LATEST=1 make docker-push
