
[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/src-d/go-log.v1"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "gopkg.in/src-d/regression-core.v0"

[prune]
  go-tests = true
  unused-packages = true
